#!/bin/sh
set -e
apt-get update -y
# install the gd
apt-get install -y --no-install-recommends \
    libfreetype6-dev \
    libjpeg-dev \
    libpng-dev \
    libmagickwand-dev

 docker-php-ext-configure gd \
      --with-gd \
      --with-freetype-dir=/usr \
      --with-png-dir=/usr \
      --with-jpeg-dir=/usr
docker-php-ext-install -j "$(nproc)" gd

apt-get install -y --no-install-recommends\
     libbz2-dev \
     libxslt-dev \
     libldap2-dev \
     libgmp-dev \
     librabbitmq-dev \
     libmemcached-dev \
     libffi-dev \
     libmcrypt-dev \
     libzip-dev  \
     librdkafka-dev

docker-php-ext-install -j "$(nproc)"  \
     exif \
     bz2 \
     bcmath \
     calendar \
     mysqli \
     fileinfo \
     pdo_mysql \
     pdo_sqlite \
     xsl \
     ldap \
     gmp \
     wddx \
     shmop \
     sockets \
     sysvmsg \
     sysvsem \
     sysvshm \
     xmlrpc \
     gettext \
     pcntl \
     iconv \
     zip \
     gettext

docker-php-pecl-install mcrypt-1.0.3
docker-php-pecl-install msgpack-2.1.1
docker-php-pecl-install memcached-3.1.5
docker-php-pecl-install redis-5.3.1
docker-php-pecl-install swoole-4.5.3
docker-php-pecl-install protobuf-3.5.1
docker-php-pecl-install grpc-1.20.0
docker-php-pecl-install imagick-3.4.4
docker-php-pecl-install yac-2.0.2
docker-php-pecl-install amqp-1.10.0
docker-php-pecl-install rdkafka-3.1.3
docker-php-pecl-install xlswriter-1.3.6