FROM dockerskr/alpine:3.15.0-v0.1


RUN apk add --no-cache \
    gcc \
    g++ \
    make \
    autoconf \
    pcre-dev \
    libxml2-dev \
    sqlite-dev \
    libcurl \
    curl-dev \
    openssl-dev \
    oniguruma-dev \
    krb5-dev \
    libpng-dev \
    libwebp-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    gettext-dev \
    libedit-dev \
    net-snmp-dev \
    libzip-dev \
    libxpm-dev



        








    
